#!/bin/sh -e

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install

if [ -d /var/db/kiss/installed/readline ] && [ /usr/share/man/man3/history.3 ]; then
rm "$1/usr/share/man/man3/history.3"
fi
