#!/bin/sh -e

./configure \
    --prefix=/usr \
    --datadir=/usr/share/openssh \
    --sysconfdir=/etc/ssh \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib/openssh \
    --without-selinux \
    --with-privsep-user=nobody \
    --with-mantype=doc \
    --without-rpath \
    --disable-strip \
    --with-ssl-engine \
    --with-pid-dir=/run \
    --disable-wtmp \
    --disable-utmp

make
make DESTDIR="$1" install

install -Dm755 contrib/ssh-copy-id "$1/usr/bin/ssh-copy-id"
install -Dm755 contrib/ssh-copy-id.1 "$1/usr/share/man/man1/ssh-copy-id.1"

# Install runit services.
install -dm755 "$1/etc/sv/sshd"
install -Dm755 sshd.run "$1/etc/sv/sshd/run"

#ln -sf /etc/sv/sshd /run/runit/
