#!/bin/sh -e

# Error appears to be harmless as sshd is installed.
#     make : .../pkg/openssh/usr/bin/sshd: No such file or directory
#     make: [Makefile:385: check-config] Error 127 (ignored)

./configure \
    --prefix=/usr \
    --datadir=/usr/share/openssh \
    --sysconfdir=/etc/ssh \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib/openssh \
    --without-selinux \
    --with-privsep-user=nobody \
    --with-mantype=doc \
    --without-rpath \
    --disable-strip \
    --with-ssl-engine \
    --with-pid-dir=/run \
    --disable-wtmp \
    --disable-utmp

make
make DESTDIR="$1" install

install -Dm755 contrib/ssh-copy-id "$1/usr/bin"
install -Dm644 contrib/ssh-copy-id.1 "$1/usr/share/man/man1"

# Install runit service.
install -Dm755 sshd.run "$1/etc/sv/sshd/run"
install -dm755 "$1/var/service"
ln -sf /etc/sv/sshd "$1/var/service/"
ln -sf /run/runit/supervise.sshd "$1/etc/sv/sshd/supervise"
