#!/bin/sh

# Generate host keys if they don't already exist.
ssh-keygen -A >/dev/null 2>&1

# Creating 'lastlog' keeps sshd log quiet.
touch /var/log/lastlog

cat <<EOF

###################################################################

NOTE: To resolve "no hostkey alg"
      add this to '/etc/ssh/sshd_config'.

-> 'HostKeyAlgorithms +ssh-rsa'

NOTE: To resolve "Unable to negotiate with ... port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss"
      add this to '/etc/ssh/ssh_config' or '.ssh/config'.

-> 'HostKeyAlgorithms +ssh-rsa'

NOTE: To allow (RSA) public key login
      add this to '/etc/ssh/sshd_config',
      '/etc/ssh/ssh_config' or '.ssh/config'.

-> 'PubkeyAcceptedAlgorithms +ssh-rsa'

NOTE: PubkeyAcceptedKeyTypes is aliased to PubkeyAcceptedAlgorithms

###################################################################

EOF
