#!/bin/sh

# Generate host keys if they don't already exist.
ssh-keygen -A >/dev/null 2>&1

cat <<EOF
####################################################################################

NOTE: To resolve "no hostkey alg" add this to '/etc/ssh/sshd_confi' and/or '~/.ssh/config'

-> 'HostKeyAlgorithms +ssh-rsa'
-> 'PubkeyAcceptedAlgorithms +ssh-rsa'

NOTE: PubkeyAcceptedKeyTypes is aliased to PubkeyAcceptedAlgorithms

####################################################################################
EOF
