#!/bin/sh -e

# Fix segmentation fault on musl by increasing stack-size.
# https://lists.alpinelinux.org/~alpine/users/%20%3CCAD4qdYDSYcp_mzBJXM6PFQsGA9xkR8_s+aWpgRTGkXwoPcx2-Q%40mail.gmail.com%3E

export CXXFLAGS="-pthread"
export LDFLAGS="-static -Wl,-z,stack-size=1048576"

sed -i \
    -e "s:-O3 -march=native:$CFLAGS:" \
    -e 's:/usr/local:/usr:' Makefile

make
make install
