#!/bin/sh -e

ver=2.4.2

unzip dnspython-$ver-py3-none-any.whl

mkdir -p "$1/usr/lib/python3.11/site-packages"

cp -R dns                  "$1/usr/lib/python3.11/site-packages"
cp -R dnspython*.dist-info "$1/usr/lib/python3.11/site-packages"
