#!/bin/sh -e

if [ "$(id -u)" != 0 ]; then
   echo "#####################################"
   echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
   echo "#                                   #"
   echo "#      ssu -p kiss b go-mtpfs       #"
   echo "#####################################"

   owner="$(ls -ld $KISSREPO/cache/sources/go-mtpfs | cut -d ' ' -f 3)"

   [ "$owner" != root ] && rm -rf $KISSREPO/cache/sources/go-mtpfs

   exit 1
fi

go build ./

install -Dm755 go-mtpfs "$1/usr/bin/go-mtpfs"
