#!/bin/sh -e

UID="$(id | cut -d "(" -f 1)"

if [ "$UID" != uid=0 ]; then
echo "#####################################"
echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
echo "#                                   #"
echo "#       ssu -p kiss b go-mtpfs      #"
echo "#####################################"
sleep 1
[ -d /var/db/kiss/cache/sources/go-mtpfs ] && \
   rm -rf /var/db/kiss/cache/sources/go-mtpfs
exit 1
fi

go build ./

install -Dm755 go-mtpfs "$1/usr/bin/go-mtpfs"
