#!/bin/sh -e

if [ "$(id -u)" != 0 ]; then
   echo "#####################################"
   echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
   echo "#                                   #"
   echo "#      ssu -p kiss b go-mtpfs       #"
   echo "#####################################"

   exit 1
fi

go build ./

install -Dm755 go-mtpfs "$1/usr/bin/go-mtpfs"
