#!/bin/sh -e

unzip ./*.zip

install -Dm755 bin/exa          "$1/usr/bin/exa"
install -Dm644 man/exa.1        "$1/usr/share/man/man1/exa.1"
install -Dm644 man/exa_colors.5 "$1/usr/share/man/man5/exa_colors.5"
