#!/bin/sh -e

sed -e "s+# DATA_FOLDER=data+DATA_FOLDER=/var/lib/vaultwarden/data+" \
    -e "s/# ROCKET_ADDRESS=0\.0\.0\.0/ROCKET_ADDRESS=127\.0\.0\.1/" \
    -e "s+# WEB_VAULT_FOLDER=web-vault\/+WEB_VAULT_FOLDER=\/var\/lib\/vaultwarden\/web-vault+" \
    -e "s/# WEBSOCKET_ENABLED=false/WEBSOCKET_ENABLED=true/" \
    -e "s+# LOG_FILE=/path/to/log+LOG_FILE=/var/log/vaultwarden.log+" .env.template > _

# Set the CARGO_HOME variable to the current directory to prevent cargo from
# touching '$HOME/.cargo'. This keeps the build contained to the package
# manager's domain.
export CARGO_HOME=$PWD

# Instruct the compiler to trim absolute paths in resulting binaries and instead
# change them to relative paths ($PWD/... ./...).
export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix=$PWD=."

# Extract each crate and generate a checksum file. This effectively mimics
# 'cargo vendor' without the network requirement. This allows the package
# manager to cache each crate and handle them as regular sources.
(
    cd vendor

    for crate in *.crate; do
        tar xf "$crate"

        # Strip the filename from the sha256sum output.
        sha256=$(sha256sum "$crate")
        sha256=${sha256%% *}

        printf '{"package":"%s","files":{}}\n' "$sha256" \
            > "${crate%.crate}/.cargo-checksum.json"
    done
)

# Cargo reads a "global" configuration file from $CARGO_HOME, as we've set it to
# $PWD this is where we'll be storing the vendor config.
mkdir -p .cargo

# Create the configuration file to tell cargo to look in the 'vendor' directory
# for the already downloaded sources rather than crates.io (over network).
cat <<EOF > .cargo/config
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

# Use the '--frozen' flag to tell cargo to skip the network and use whatever
# dependencies are in the Cargo.[toml|lock] files.
cargo clean
cargo build --features sqlite --release --frozen

install -Dm755 target/release/vaultwarden "$1/usr/bin/vaultwarden"
install -Dm640 _                          "$1/etc/vaultwarden.conf"
install -dm750                            "$1/var/lib/vaultwarden/data"

mv web-vault "$1/var/lib/vaultwarden"

# Install runit service.
install -Dm755 vaultwarden.run "$1/etc/sv/vaultwarden/run"
ln -sf /run/runit/supervise.vaultwarden "$1/etc/sv/vaultwarden/supervise"
