#!/bin/sh -e

getent group vaultwarden || addgroup -S -g 989 vaultwarden
getent passwd vaultwarden || adduser -H -h /var/lib/vaultwarden -s /usr/bin/false -D -S -G vaultwarden -u 989 -g "Unprivileged User" vaultwarden

chown root:vaultwarden /usr/bin/vaultwarden
chown -R vaultwarden:vaultwarden /var/lib/vaultwarden
chown vaultwarden:vaultwarden /etc/vaultwarden.conf
chown vaultwarden:vaultwarden /var/log/vaultwarden

cat <<EOF

###########################################

NOTE: Install 'Bitwarden CLI' with

-> npm install -g @bitwarden/cli

NOTE: Useage

-> NODE_EXTRA_CA_CERTS=root.crt bw login
-> NODE_TLS_REJECT_UNAUTHORIZED=0 bw login

###########################################

EOF
