#!/bin/sh -e

getent group vaultwarden || addgroup -S -g 989 vaultwarden
getent passwd vaultwarden || adduser -H -h /var/lib/vaultwarden -s /usr/bin/false -D -S -G vaultwarden -u 989 -g "Unprivileged User" vaultwarden

chown root:vaultwarden /usr/bin/vaultwarden
chown -R vaultwarden:vaultwarden /var/lib/vaultwarden
chown vaultwarden:vaultwarden /etc/vaultwarden.conf
chown vaultwarden:vaultwarden /var/log/vaultwarden.log

cat <<EOF

###########################################

NOTE: As there is no musl binary of 'Bitwarden CLI',
      it needs to be installed with nodejs.

-> kiss build nodejs

NOTE: Install latest 'Bitwarden CLI'.

-> npm install -g @bitwarden/cli

NOTE: List 'Bitwarden CLI' versions.

-> npm view @bitwarden/cli versions

NOTE: Install specific 'Bitwarden CLI' version.

-> npm install -g @bitwarden/cli@x.y.z

NOTE: Useage

-> NODE_EXTRA_CA_CERTS=root.crt bw login
-> NODE_TLS_REJECT_UNAUTHORIZED=0 bw login

NOTE: The 'root.crt' certificate is created
      by caddy.

###########################################

EOF
