#!/bin/sh -e

cat <<EOF

###############################################
#                                             #
#    [ ! ]  WARNING WARNING WARNING  [ ! ]    #
#                                             #
#             REMOVING VAULTWARDEN            #
#                     WILL                    #
#                 REMOVE VAULT                #
#                                             #
###############################################

EOF

echo "Do you wish to remove Vaultwarden?"
echo -n "yes/no: "
read -r ans

if [ "$ans" = "yes" ]; then
   [ -f /etc/sv/vaultwarden/supervise/stat ] && status="$(cat /etc/sv/vaultwarden/supervise/stat)"

   [ "$status" = "run" ] && sv down vaultwarden

   deluser --remove-home vaultwarden

   rm  -f \
        "/etc/vaultwarden.conf" \
        "/var/log/vaultwarden.log"

   rm -rf \
        "/etc/sv/vaultwarden" \
        "/run/runit/supervise.vaultwarden" \
        "/var/service/vaultwarden"

else [ "$ans" != "yes" ]
     echo "Aborting Vaultwarden removal."
     exit 1

fi
