#!/bin/sh -e

cat <<EOF

###########################################
#   [ ! ] WARNING WARNING WARNING [ ! ]   #
#                                         #
#  Removing vaultwarden WILL remove vault #
#                                         #
###########################################

EOF

echo "Do you wish to remove Vaultwarden?"
echo -n "yes/no: "
read -r ans

if [ "$ans" = yes ]; then
   sv down vaultwarden
   deluser --remove-home vaultwarden
   unlink /var/service/vaultwarden
   rm -r /etc/sv/vaultwarden
else
   echo "Aborting Vaultwarden removal."
   exit 1
fi
