#!/bin/sh -e

cat <<EOF

###############################################
#                                             #
#    [ ! ]  WARNING WARNING WARNING  [ ! ]    #
#                                             #
#             REMOVING VAULTWARDEN            #
#                     WILL                    #
#                 REMOVE VAULT                #
#                                             #
###############################################

EOF

echo "Do you wish to remove Vaultwarden?"
echo -n "yes/no: "
read -r ans

if [ "$ans" = yes ]; then
   status=$(cat /etc/sv/vaultwarden/supervise/stat)
   [ "$status" = "run" ] && sv down vaultwarden
   deluser --remove-home vaultwarden
   [ -L /var/service/vaultwarden ] && unlink /var/service/vaultwarden
   rm -r \
       "/etc/vaultwarden.conf" \
       "/etc/sv/vaultwarden" \
       "/run/runit/supervise.vaultwarden"
else
   echo "Aborting Vaultwarden removal."
   exit 1
fi
