#!/bin/sh -e

BINOWN="$(id -u)" \
BINGRP="$(id -g)" \

./configure \
    --prefix=/usr \
    --enable-static \
    --with-shadow \
    --with-timestamp \
    --without-pam

make
make install

install -Dm600 doas.conf "$1/etc/doas.conf"
