#!/bin/sh -e

sed 's+<ncursesw/ncurses.h>+<ncurses.h>+' stfl_internals.h > _
mv -f _ stfl_internals.h

sed 's+/usr/local+/usr+' Makefile.cfg > _
mv -f _ Makefile.cfg

make
make DESTDIR="$1" install

ln -s libstfl.so.0.24 "$1/usr/lib/libstfl.so.0"
