#!/bin/sh -e

unzip master.zip
cd stfl-master

sed -i 's+<ncursesw/ncurses.h>+<ncurses.h>+' stfl_internals.h
sed -i 's+/usr/local+/usr+' Makefile.cfg

make
make DESTDIR="$1" install

ln -s libstfl.so.0.24 "$1/usr/lib/libstfl.so.0"
