#!/bin/sh -e

# "GNU Make 4.3" can hang due to Makefile.
#     -> "git shortlog -s -n | cut -f2 | sort > AUTHORS"
#
# Use one of these options to allow 'make' to continue.
#    "bash+starship"
#    "make </dev/null"
#    "sed -i '/< AUTHORS/d' Makefile"

make </dev/null

install -Dm755 yt-dlp   "$1/usr/bin/yt-dlp"
install -Dm644 yt-dlp.1 "$1/usr/share/man/man1/yt-dlp.1"
