#!/bin/sh -e

install -Dm755 testdisk_static  "$1/usr/bin/testdisk"
install -Dm755 photorec_static  "$1/usr/bin/photorec"
install -Dm755 fidentify_static "$1/usr/bin/fidentify"

install -Dm644 -t "$1/usr/share/man/man8" testdisk.8 photorec.8 fidentify.8
