#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

./configure \
    --prefix=/usr \
    --program-prefix=g

make
make install

# Purge locale messages + remote magnetic tape server (rmt).
rm -rf "$1/usr/share/locale" \
       "$1/usr/libexec" \
       "$1/usr/share/man/man8"

