#!/bin/sh -e

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --enable-really-static

make
make install

# Move all bin's to singular dir.
mv -f "$1/bin/"*3g "$1/usr/bin"

# Create assorted symlinks.
ln -sf ntfsfix "$1/usr/bin/fsck.ntfs"
ln -sf ntfs-3g "$1/usr/bin/mount.ntfs-3g"
ln -sf lowntfs-3g "$1/usr/bin/mount.lowntfs-3g"
ln -sf ntfsfix.8 "$1/usr/share/man/man8/fsck.ntfs.8"

# Pkg cleanup.
rm -rf \
     "$1/bin" \
     "$1/sbin" \
     "$1/usr/lib" \
     "$1/usr/share/doc"
