#!/bin/sh

# As an alternative to the .conf file separate files can be used for varibles.
#    /etc/vaultwarden/DATA_FOLDER -> /var/lib/vaultwarden/data
#    /etc/vaultwarden/WEB_VAULT_FOLDER -> /var/lib/vaultwarden/web-vault
# export envdir=/etc/vaultwarden
# exec chpst -u vaultwarden:vaultwarden -e "$envdir" /usr/bin/vaultwarden

export ENV_FILE=/etc/vaultwarden.conf
exec chpst -u vaultwarden:vaultwarden /usr/bin/vaultwarden >/dev/null 2>&1
