#!/bin/sh -e
 
./configure --prefix=/usr

make
make DESTDIR="$1" install

rm "$1/usr/share/detox/safe.tbl"
install -Dm644 safe.tbl "$1/usr/share/detox/safe.tbl"

rm "$1/usr/etc/detoxrc"
install -Dm644 detoxrc "$1/usr/etc/detoxrc"
