#!/bin/sh -e

# Remove nonexistant compress option.
sed 's/lzip -z/lzip   /' kiss > _

# https://www.nongnu.org/lzip/plzip.html
# "Plzip can compress/decompress large files
#  on multiprocessor machines much faster than lzip,
#  at the cost of a slightly reduced compression ratio"
sed 's/lzip/plzip/' _ > __
mv -f __ kiss

chmod +x kiss

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/doc/kiss"

cp -f  kiss contrib/*  "$1/usr/bin"
cp -f  docs/site/*.txt "$1/usr/share/doc/kiss"
cp -rf docs/site/wiki  "$1/usr/share/doc/kiss"

rm -f \
    "$1/usr/share/doc/kiss/README.txt" \
    "$1/usr/share/doc/kiss/post.txt" \
    "$1/usr/share/doc/kiss/tidbits.txt" \
    "$1/usr/share/doc/kiss/package-manager.txt" \
    "$1/usr/share/doc/kiss/package-system.txt"

