#!/bin/sh -e

# Remove non-existant lzip compress option.
# Remove non-existant digest (cppcrypto) option.
sed \
    -e 's/lzip -z/lzip   /' \
    -e 's/digest) set -- -a sha256/digest) set -- sha256/' kiss > _

# https://www.nongnu.org/lzip/plzip.html
# "Plzip can compress/decompress large files
#  on multiprocessor machines much faster than lzip,
#  at the cost of a slightly reduced compression ratio"
#
# Compressing llvm with plzip is around 8mins faster
# then lzip with just a slight increase in archive size.
sed 's/lzip/plzip/' _ > __
mv -f __ kiss

chmod +x kiss

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/doc/kiss"

cp -f  kiss contrib/*  "$1/usr/bin"
cp -f  docs/site/*.txt "$1/usr/share/doc/kiss"
cp -rf docs/site/wiki  "$1/usr/share/doc/kiss"

rm -f \
    "$1/usr/share/doc/kiss/README.txt" \
    "$1/usr/share/doc/kiss/post.txt" \
    "$1/usr/share/doc/kiss/tidbits.txt" \
    "$1/usr/share/doc/kiss/package-manager.txt" \
    "$1/usr/share/doc/kiss/package-system.txt"
