#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --with-mini-gmp \
    --with-cli=readline \
    --disable-debug

make
make install

# Remove examples.
rm -rf "$1/usr/share/doc"
