#!/bin/sh -e

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --mandir=/usr/share/man \
    --libexecdir=/usr/lib \
    --disable-nls \
    --disable-rpath \
    --disable-mouse \
    --disable-external-uri-loader \
    --disable-w3mmailer \
    --disable-m17n

make
make DESTDIR="$1" install

# Remove docs.
rm -rf \
     "$1/usr/share/man/de" \
     "$1/usr/share/man/ja" \
     "$1/usr/share/w3m"/*.de.pl \
     "$1/usr/share/w3m"/*.ja.pl
