#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

./configure \
    --prefix=/usr \
    --without-bash-malloc \
    --without-installed-readline \
    --disable-nls

make
# Build fails without "DESTDIR".
make DESTDIR="$1" install

rm -r "$1/usr/share/doc"

ln -s bash "$1/usr/bin/sh"
