#!/bin/sh

cat <<EOF

#########################################

NOTE: To change the login shell by using 'chsh'.

      # Install 'shadow'.
      -> kiss build shadow

      # Add this to '/etc/shells'.
      -> /bin/bash

      # Change shell.
      -> chsh --shell /bin/bash

NOTE: To change the login shell manually
      edit '/etc/passwd'.

NOTE: To enable Eternal Bash History
      add this to '~/.profile'.

# ------ BEGIN ------ #
# ---------------------
# Eternal Bash History.
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
# ------- END ------- #

NOTE: Changing the login shell can erase
      HISTFILE=~/.bash_eternal_history.

#########################################

EOF

