#!/bin/sh -e

# Change to more visible colour for URLs.
sed -i 's/lightblue/green/' syntax/default.nanorc

./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make
make DESTDIR="$1" install

sed '/# set tabsize 8/a\set tabsize 4' doc/sample.nanorc > _
install -Dm644 _ "$1/etc/nanorc"
