#!/bin/sh -e

ver=2.7.6

if [ "$(id -u)" != 0 ]; then
   echo "#####################################"
   echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
   echo "#                                   #"
   echo "#        ssu -p kiss b caddy        #"
   echo "#####################################"

   exit 1
fi

die () {
   echo "ERROR: caddy "$ver" requires a newer version of 'go', such as >='go1.20.1'"
   exit 1
}

[ "$(go version | cut -d' ' -f3)" = "go1.18.2" ] && die

TMPDIR="$(mktemp -d -p .)"

tar xf ../../../../sources/caddy/caddy_"$ver"_src.tar.gz -C "$TMPDIR"

cd "$TMPDIR/cmd/caddy"

go build

install -Dm755 caddy "$1/usr/bin/caddy"
install -dm700 "$1/etc/caddy"
install -Dm644 ../../../Caddyfile-example "$1/etc/caddy/Caddyfile"
install -Dm755 ../../../caddy.run "$1/etc/sv/caddy/run"
install -dm700 "$1/var/lib/caddy/"
install -dm755 "$1/var/log/caddy/"

# Install runit service.
install -dm755 "$1/var/service"
ln -sf /etc/sv/caddy "$1/var/service/"
ln -sf /run/runit/supervise.caddy "$1/etc/sv/caddy/supervise"
