#!/bin/sh -e

vers=2.7.6

if [ "$(id -u)" != 0 ]; then
   echo "#####################################"
   echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
   echo "#                                   #"
   echo "#        ssu -p kiss b caddy        #"
   echo "#####################################"

   owner="$(ls -ld $KISSREPO/cache/sources/caddy | cut -d ' ' -f 3)"

   [ "$owner" != root ] && rm -rf $KISSREPO/cache/sources/caddy

   exit 1
fi

TMPDIR="$(mktemp -d -p .)"

tar xf ../../../../sources/caddy/caddy_$vers_src.tar.gz -C "$TMPDIR"
cd "$TMPDIR/cmd/caddy"

go build

install -Dm755 caddy "$1/usr/bin/caddy"
install -dm700 "$1/etc/caddy"
install -Dm644 ../../../Caddyfile-example "$1/etc/caddy/Caddyfile"
install -Dm755 ../../../caddy.run "$1/etc/sv/caddy/run"
install -dm755 "$1/var/service/"
install -dm700 "$1/var/lib/caddy/"
install -dm755 "$1/var/log/caddy/"

ln -sf /etc/sv/caddy "$1/var/service/"
