#!/bin/sh -e

UID="$(id | cut -d "(" -f 1)"

if [ "$UID" != uid=0 ]; then
echo "#####################################"
echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
echo "#                                   #"
echo "#        ssu -p kiss b caddy        #"
echo "#####################################"
sleep 1
[ -d /var/db/kiss/cache/sources/caddy ] && \
   rm -rf /var/db/kiss/cache/sources/caddy
exit 1
fi

cd cmd/caddy

go build

install -Dm755 caddy "$1/usr/bin/caddy"
install -dm700 "$1/etc/caddy"
install -Dm644 ../../Caddyfile-example "$1/etc/caddy/Caddyfile"
install -Dm755 ../../caddy.run "$1/etc/sv/caddy/run"
install -dm755 "$1/var/service/"
install -dm700 "$1/var/lib/caddy/"
install -dm755 "$1/var/log/caddy/"

ln -sf /etc/sv/caddy "$1/var/service/"
