#!/bin/sh -e

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --sysconfdir=/etc \
    --disable-account-tools-setuid \
    --with-group-name-max-length=32 \
    --without-audit \
    --without-selinux \
    --without-libpam \
    --disable-shared \
    --enable-static

make
make DESTDIR="$1" install

install -m755 -t "$1/usr/bin" src/id src/sulogin

for f in 1 5 8; do
    install -Dm644 -t "$1/usr/share/man/man$f" "man/man$f/"*.$f
done

# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"

