#!/bin/sh -e

export LDFLAGS=--static

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --enable-libuuid \
    --enable-libblkid \
    --enable-fsck \
    --disable-makeinstall-chown \
    --disable-last \
    --disable-liblastlog2 \
    --disable-rpath \
    --without-udev \
    --without-python \
    --without-systemd \
    --disable-shared \
    --enable-static \
    --disable-minix \
    --disable-bfs \
    --disable-cramfs \
    --disable-uuidd \
    --disable-nls \
    --disable-kill \
    --disable-utmpdump

make
make install

# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"

rm -rf \
    "$1/usr/share/doc" \
    "$1/usr/share/bash-completion"

