#!/bin/sh -e

# Fix hardcoded `gcc` ( there is HOST_CC := $(CC) on line after this,
# but upstream seems to use it inconsistently ). Otherwise build fails on
# `clang` based systems with no `gcc` installed.
sed -i 's/CC := gcc/CC ?= gcc/' Makefile

# Remove unneeded utilities & manpages.
sed -i \
    -e '/ARPD/d' \
    -e 's/ netem / /' \
    -e 's/ tc / /' \
    -e 's/ tipc / /' \
    -e 's/ rdma / /' Makefile

sed -i \
    -e 's/ man3//' \
    -e 's/ man7//' man/Makefile

rm -f \
    man/man8/arpd.8 \
    man/man8/tc*.8 \
    man/man8/tipc*.8 \
    man/man8/rdma*.8

./configure \
    --prefix=/usr

# Prevent libelf from being used.
sed -i \
    -e '/HAVE_ELF/d' \
    -e '/elf/d' config.mk

make
make DESTDIR="$1" SBINDIR="/usr/bin" install

install -Dm0644 include/libnetlink.h "$1/usr/include/libnetlink.h"
install -Dm0644 lib/libnetlink.a     "$1/usr/lib/libnetlink.a"

# Cleanup.
rm -rf \
    "$1/usr/include/iproute2" \
    "$1/usr/share/bash-completion" \
    "$1/usr/share/iproute2/bpf_pinning"
