#!/bin/sh -e

./configure \
     --prefix=/usr \
     --without-zenmap \
     --with-libpcap=included
     
make
make DESTDIR="$1" install

# Remove docs
for d in de es fr hr hu it ja pl pt_BR pt_PT ro ru sk zh; do
    rm -r "$1"/usr/share/man/"$d"
    done

