#!/bin/sh -e

export CFLAGS="$CFLAGS -static"
# export FORCE_UNSAFE_CONFIGURE=1 # required if building as root

./configure \
    --prefix=/usr \
    --enable-no-install-program=kill,uptime

make
make DESTDIR="$1" install

ln -s "$1/usr/bin/cp" "$1/usr/bin/gcp"
