#!/bin/sh -e

export CFLAGS="$CFLAGS -static"
# Uncomment if building as the 'root' user.
# export FORCE_UNSAFE_CONFIGURE=1

./configure \
    --prefix=/usr \
    --enable-no-install-program=kill,uptime

make
make DESTDIR="$1" install

# Rename 'cp' to coexist with 'cp' from busybox.
mv -f "$1/usr/bin/cp" "$1/usr/bin/gcp"

