#!/bin/sh -e

export CFLAGS="$CFLAGS -static"
# Uncomment if building as the 'root' user.
# export FORCE_UNSAFE_CONFIGURE=1

./configure \
    --prefix=/usr \
    --enable-no-install-program=kill,uptime

make
make DESTDIR="$1" install

# coreutils 'cp' has more options then
# busybox 'cp',rename so they can coexist.
mv -f "$1/usr/bin/cp" "$1/usr/bin/gcp"
