#!/bin/sh

cat <<EOF

##########################################

NOTE: Busybox & Coreutils 'cp' options differ.

      Coreutils 'cp' has been renamed to 'gcp'.

##########################################

EOF
