#!/bin/sh

echo "##############################################"
echo "# As Busybox & Coreutils 'cp' options differ #"
echo "# coreutils 'cp' has been renamed to 'gcp'   #"
echo "##############################################"
