#!/bin/sh -e

sed 's+/usr/local+/usr+' Makefile > _
mv -f _ Makefile

sed 's+/usr/local+/usr+' libfuse/Makefile > _
mv -f _ libfuse/Makefile

make LTO=1
make DESTDIR="$1" install

ln -s /usr/bin/mount.fuse3 "$1/usr/bin/mount.fuse"
