#!/bin/sh -e

sed 's+/usr/local+/usr+' Makefile > _
mv -f _ Makefile

sed 's+/usr/local+/usr+' libfuse/Makefile > _
mv -f _ libfuse/Makefile

make LTO=1

install -Dm755 build/mergerfs $1/usr/bin/mergerfs
install -Dm4755 libfuse/build/mergerfs-fusermount $1/usr/bin/mergerfs-fusermount
install -Dm644 man/mergerfs.1 $1/usr/share/man/man1/mergerfs.1

ln -s /usr/bin/mount.fuse3 "$1/usr/bin/mount.fuse"
