#!/bin/sh -e

# Remove 'libelf' dependency.
sed 's/HAVE_LIBELF/HAVE_KISS/' gio/meson.build > _
mv -f _ gio/meson.build

# Remove 'util-linux' dependency.
sed 's/libmount_dep.found()/false/' meson.build > _
mv -f _ meson.build

# The file 'mesom.build' allows build to succeed.
: > glib/tests/meson.build
: > tests/meson.build
: > gobject/tests/mesom.build
: > gio/tests/meson.build
: > fuzzing/meson.build

meson \
    --prefix=/usr \
    -Dlibmount=disabled \
    -Dinstalled_tests=false \
    -Ddefault_library=both \
    -Dman=false \
    -Dfam=false \
    . build

ninja -C build
ninja -C build install

rm -rf "$1/usr/bin/gdbus"

# Auto detection appears wonky as '/usr/share/bash-completion' is not
# always included and the contents of '/usr/share/gettext' changes.
rm -rf \
     "$1/usr/share/gettext" \
     "$1/usr/share/bash-completion"
