#!/bin/sh -e
#
# Build fails as USER chown: changing ownership of pkg/fcron/usr/sbin : Operation not permitted

sed 's/ fr//' doc/Makefile.in > _
mv -f _ doc/Makefile.in

sed '25s/sbindir/bindir/' Makefile.in > _
mv -f _ Makefile.in

sed 's+-O2++g' configure > _
mv -f _ configure

./configure \
    --prefix=/usr \
    --with-boot-install=no \
    --with-systemdsystemunitdir=no \
    --with-docdir=/usr/share/doc \
    --localstatedir=/var \
    --mandir=/usr/share/man \
    --sysconfdir=/etc
        
        
make
make DESTDIR="$1" install

install -dm755 $1/etc/cron.{hourly,daily,weekly,monthly}

install -m640 systab.orig $1/var/spool/fcron
install -m755 run-parts $1/usr/bin

# Install runit services.
install -Dm755 fcron.run $1/etc/sv/fcron/run
install -dm755 $1/var/service

ln -sf /etc/sv/fcron $1/var/service/
