#!/bin/sh -e
#
# Build fails as USER chown: changing ownership of pkg/fcron/usr/sbin : Operation not permitted

getent group fcron || addgroup -S -g 997 fcron
getent passwd fcron || adduser -H -h /var/spool/fcron -s /bin/sh -D -S -G fcron -u 997 -g "Unprivileged User" fcron

sed 's/ fr//' doc/Makefile.in > _
mv -f _ doc/Makefile.in

./configure \
        --prefix=/usr \
        --with-boot-install=no \
        --with-docdir=/usr/share/doc \
        --localstatedir=/var \
        --mandir=/usr/share/man \
        --sysconfdir=/etc
        
make
make DESTDIR="$1" install

install -vdm755 /etc/cron.hourly
install -vdm755 /etc/cron.daily
install -vdm755 /etc/cron.week
install -vdm755 /etc/cron.monthly

install -m640 $KISSREPO/repo/extra/fcron/files/systab.orig $1/var/spool/fcron/systab.orig
install -m755 $KISSREPO/repo/extra/fcron/files/run-parts $1/usr/bin/run-parts

# Install runit services.
install -dm755 "$1/etc/sv/fcron"
install -m755 $KISSREPO/repo/extra/fcron/files/fcron.run "$1/etc/sv/fcron/run"
ln -sf /etc/sv/fcron /var/service/
