#!/bin/sh -e

getent group fcron || addgroup -S -g 997 fcron
getent passwd fcron || adduser -H -h /var/spool/fcron -s /bin/sh -D -S -G fcron -u 997 -g "Unprivileged User" fcron

# fix permissions and owners
	chown fcron:fcron /usr/bin/fcrontab /usr/bin/fcrondyn
	chown root:fcron /usr/bin/fcronsighup
	chmod  110 /usr/bin/fcron
	chmod 4110 /usr/bin/fcronsighup
	chmod 6111 /usr/bin/fcrontab /usr/bin/fcrondyn

	chown root:fcron /etc/fcron.conf /etc/fcron.allow /etc/fcron.deny
	chmod  640 /etc/fcron.conf /etc/fcron.allow /etc/fcron.deny
	chown fcron:fcron /var/spool/fcron

fcrontab /var/spool/fcron/systab.orig

cat <<EOF

NOTE: If $USER's shell is "/usr/bin/bash" and the system shell is "busybox /usr/bin/sh"

roots fcrontab will fail to run command as $USER unless the system shell is changed to

"bash /usr/bin/sh" or "/etc/fcron.conf" "shell = /usr/bin/sh" is changed to "/usr/bin/bash"

EOF
