#!/bin/sh -e

getent group fcron || addgroup -S -g 997 fcron
getent passwd fcron || adduser -H -h /var/spool/fcron -s /bin/sh -D -S -G fcron -u 997 -g "Unprivileged User" fcron

# fix permissions and owners
	chown fcron:fcron /usr/bin/fcrontab /usr/bin/fcrondyn
	chown root:fcron /usr/bin/fcronsighup
	chmod  110 /usr/bin/fcron
	chmod 4110 /usr/bin/fcronsighup
	chmod 6111 /usr/bin/fcrontab /usr/bin/fcrondyn

	chown root:fcron /etc/fcron/fcron.conf /etc/fcron/fcron.allow /etc/fcron/fcron.deny
	chmod  640 /etc/fcron/fcron.conf /etc/fcron/fcron.allow /etc/fcron/fcron.deny
	chown fcron:fcron /var/spool/fcron

fcrontab /var/spool/fcron/systab.orig

cat <<EOF

######################################################

NOTE: If the system shell is "/usr/bin/sh -> busybox",
      roots fcrontab entry may fail to run as "$USER".

      Set shell used by fcron in "/etc/fcron/fcron.conf"
      or with "kiss a bash /usr/bin/sh".

######################################################

EOF
