#!/bin/sh -e

# These files are (modified) & not removed despite contents being unchanged.
# /etc/fcron.conf
# /etc/fcron.allow
# /etc/fcron.deny
# /etc/sv/fcron/run

sv down fcron
deluser --remove-home fcron
unlink /var/service/fcron
rm -r  /etc/sv/fcron
rm     /etc/fcron.*

cat <<EOF

######################################

[!] Reboot to resolve the following errors [!]

runsv: can't move 'supervise/stat.new' to 'supervise/stat': No such file or directory runsv
fcron: warning: cannot open supervise/status.new: No such file or directory runsv
fcron: warning: cannot open supervise/pid.new: No such file or directory

######################################

EOF
