#!/bin/sh -e

if [ -L /var/service/fcron ]; then
   sv down fcron
   unlink /var/service/fcron
fi

deluser --remove-home fcron

# NOTE: These files are (modified) & not removed despite contents being unchanged.
# /etc/fcron.conf
# /etc/fcron.allow
# /etc/fcron.deny
# /etc/sv/fcron/run

rm -r \
    "/etc/sv/fcron" \
    "/run/runit/supervise.fcron"

rm  /etc/fcron.*

cat <<EOF

######################################

NOTE: Reboot to resolve the following errors.

runsv: can't move 'supervise/stat.new' to 'supervise/stat': No such file or directory runsv
fcron: warning: cannot open supervise/status.new: No such file or directory runsv
fcron: warning: cannot open supervise/pid.new: No such file or directory

######################################

EOF
