#!/bin/sh -e

# Berkeley DB 6.0.19 is the last Sleepycat license version
# not 5.3.28 as per netatalk docs.

ver=5.3

sed 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' src/dbinc/atomic.h > _
mv -f _ src/dbinc/atomic.h

cd build_unix

../dist/configure prefix=/usr \
                  --disable-shared \
                  --libdir=/opt/BerkeleyDB.$ver/lib \
                  --includedir=/opt/BerkeleyDB.$ver/include \
                  docdir=${exec_prefix}/docs

make
make install

# Fix permissions for stripping.
chmod 755 "$1/usr/bin/"*

# Append "$ver" to binaries.
for bin in "$1/usr/bin/"*; do
    mv "$bin" "$bin$ver"
done

# Remove 20Mb of docs.
rm -rf "$1/usr/docs"
