#!/bin/sh

cat << EOF

######################################

NOTE: To configure ngetty refer to the
      manpage 'ngetty.8' and
      '/usr/share/ngetty/sample.Conf'.

NOTE: To list unused virtual terminals
      run the command 'lsvt' as root.

######################################

EOF
