#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-static \
    --disable-tiff \
    --disable-gif \
    --disable-jpeg \
    --disable-png \
    --enable-libwebpmux \
    --enable-libwebpdemux \
    --enable-libwebpdecoder

make
make install
