#!/bin/sh -e

cd socklog*

sed -i 's/-s/-static/' src/conf-ld

package/compile

install -Dm755 -t "$1/usr/bin" command/*
install -Dm755 -t "$1/usr/share/man/man1" man/*.1
install -Dm755 -t "$1/usr/share/man/man8" man/*.8
