#!/bin/sh

getent group socklog || addgroup -S -g 990 socklog

# Create service files.
socklog-conf unix nobody root
# socklog-conf ucspi-tcp nobody root
# socklog-conf inet nobody root

chgrp -R socklog /var/log/socklog

find /var/log/socklog -type d -exec chmod g=u-w+s,o= '{}' +

sed -i 's/chpst -uroot svlogd/svlogd -tt/' /etc/sv/socklog-unix/log/run

chmod 755 /etc/sv/socklog-unix         # default 750
chmod 755 /etc/sv/socklog-unix/run     # default 750
chmod 755 /etc/sv/socklog-unix/log/run # default 750

# Install runit service.
ln -sf /run/runit/supervise.socklog-unix     /etc/sv/socklog-unix/supervise
ln -sf /run/runit/supervise.socklog-unix-log /etc/sv/socklog-unix/log/supervise

