#!/bin/sh

if [ -L /var/service/socklog-unix ]; then
    sv down socklog-unix
    unlink /var/service/socklog-unix
fi

delgroup socklog

rm -rf \
    "/etc/sv/socklog-unix" \
    "/var/log/socklog" \
    "/run/runit/supervise.socklog-unix" \
    "/run/runit/supervise.socklog-unix-log"

