#!/bin/sh -e

export CFLAGS="$CFLAGS -flto --static"

./autogen.sh
./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --disable-shared \
    --enable-static \
    --without-lz4

make
make install
