#!/bin/sh -e

# ipmitool & freeipmi failed to build.
#
# The shared library needs to be disabled
# so ALL binaries can be made static.
export LDFLAGS="$LDFLAGS -static"

# Fix broken --disable-shared.
sed -i '/SHR_LINK="libipmiutil.so.1"/d' configure.ac

./beforeconf.sh
./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --disable-dependency-tracking

chmod +x install-sh

make
make DESTDIR="$1" install

# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"

# Replace .gz man8's with non-compressed versions.
rm -f "$1/usr/share/man/man8/"*.8.gz
install -m644 -t "$1/usr/share/man/man8" doc/*.8

# Purge systemd related files.
rm -rf "$1/usr/share/ipmiutil" \
       "$1/etc"
