#!/bin/sh -e

if [ "$(id -u)" != 0 ]; then
    printf '%s' '
#####################################
#                                   #
# [ ! ] NEED TO BUILD AS ROOT [ ! ] #
#                                   #
#        ssu -p kiss b micro        #
#                                   #
#####################################
'
    exit 1
fi

make build

install -Dm755 micro                    "$1/usr/bin/micro"
install -Dm644 assets/packaging/micro.1 "$1/usr/share/man/man1/micro.1"
