#!/bin/sh -e

UID="$(id | cut -d "(" -f 1)"

if [ "$UID" != uid=0 ]; then
echo "#####################################"
echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
echo "#                                   #"
echo "#        ssu -p kiss b micro        #"
echo "#####################################"
sleep 1
[ -d  /var/db/kiss/cache/sources/micro ] && \
   rm -rf /var/db/kiss/cache/sources/micro
exit 1
fi

make build

install -Dm755 micro "$1/usr/bin/micro"
install -Dm644 assets/packaging/micro.1 "$1/usr/share/man/man1/micro.1"
