#!/bin/sh -e

libtoolize --force --copy --automake
aclocal
autoheader
automake --foreign --copy --add-missing
autoconf

./configure \
     --enable-shared=yes \
     --enable-static=no

make
make DESTDIR="$1" install
