#!/bin/sh -e

ver=2.7.0-beta.2

tar xf ../../../../sources/caddy-bin/caddy_"$ver"_linux_amd64.tar.gz

install -Dm755 caddy "$1/usr/bin/caddy-bin"
install -Dm644 Caddyfile-example "$1/etc/caddy/Caddyfile"
install -Dm755 caddy.run "$1/etc/sv/caddy/run"

# Install runit service.
install -dm755 "$1/var/service"
ln -sf /etc/sv/caddy "$1/var/service/"
ln -sf /run/runit/supervise.caddy "$1/etc/sv/caddy/supervise"
