#!/bin/sh -e

cat <<EOF

################################

NOTE: Update 'go1.18.2' to >='go1.20.1'
      otherwise some updated packages will
      fail to build.

################################

EOF
