#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib/gnupg \
    --disable-gnutls \
    --enable-symcryptrun \
    --enable-gpg-is-gpg2 \
    --disable-ldap \
    --disable-nls \
    --disable-rpath \
    --disable-sqlite \
    --disable-card-support \
    --disable-tests \
    --disable-doc

make
make DESTDIR="$1" install

ln -sf gpg2  "$1/usr/bin/gpg"
ln -sf gpgv2 "$1/usr/bin/gpgv"

