#!/bin/sh -e

mv Modules/* cmake/modules/

# Using CFLAGS='-pipe' causes 'cmake' & 'llvm' to use the same build folder,
# thus causing the resultant link to become '../cmake/Modules/modules'.
# which intern causes 'llvm' to fail building due to missing files.

if [ -d ../cmake/Modules ]; then
    for f in "$(pwd)/cmake/modules"/*; do
        ln -s "$f" ../cmake/Modules
    done
else
    # Fix lifted from https://github.com/noirlinux/main/blob/master/extra/llvm/build
    # Create a symbolic link to the expected folder
    mkdir -p ../cmake && ln -s "$(pwd)/cmake/modules" ../cmake/Modules
fi

# Remove ncurses dependency.
sed 's/\(LLVM_ENABLE_TERMINFO\) 1/\1 2/' \
    cmake/config-ix.cmake > _
mv -f _ cmake/config-ix.cmake

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_BUILD_LLVM_DYLIB=ON \
    -DLLVM_LINK_LLVM_DYLIB=ON \
    -DLLVM_TARGETS_TO_BUILD="host;AMDGPU" \
    -DLLVM_ENABLE_RTTI=ON \
    -DLLVM_HOST_TRIPLE="$(cc -dumpmachine)" \
    -DLLVM_INCLUDE_BENCHMARKS=OFF \
    -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_INCLUDE_DOCS=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_ENABLE_TERMINFO=OFF \
    -DLLVM_ENABLE_LIBXML2=OFF \
    -DLLVM_ENABLE_LIBEDIT=OFF \
    -Wno-dev

cmake --build   build
cmake --install build
