#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

./configure \
    --prefix=/usr \
    --localstatedir=/var/lib/locate \
    --libexecdir=/usr/share/lib \
    --disable-nls \
    --disable-rpath

make
make install
