#!/bin/sh -e

make
make install

# Fix 'strip' permission errors.
find "$1/opt/schily/lib" -name "*.a"   -exec chmod 644 '{}' \;
find "$1/opt/schily/lib" -name "*.so*" -exec chmod 644 '{}' \;

# Create symlink so it can be used with
# 'kiss' without needing to set PATH.
install -dm755 "$1/usr/bin"
ln -s "/opt/schily/bin/suntar" "$1/usr/bin"

# Remove documentation (READMEs, binaries, etc).
for bin in calltree mt smt sformat sccs; do
    rm -f "$1/opt/schily/bin/$bin"
done

find "$1" -type f -name \*sccs\* -delete
find "$1" -type f -name \*rmt\*  -delete

for man in admin.1 cdc.1 comb.1 delta.1 get.1 help.1 mountcd.1 \
           prs.1 prt.1 rmdel.1 sact.1 smt.1 mt.1 unget.1 val.1 what.1; do
    rm -f "$1/opt/schily/share/man/man1/$man"
done

rm -f \
    "$1/etc/sformat.dat" \
    "$1/etc/default/rscsi" \
    "$1/opt/schily/share/man/man8/sformat.8"

rm -rf \
    "$1/etc/default/rscsi" \
    "$1/opt/schily/ccs" \
    "$1/opt/schily/sbin" \
    "$1/opt/schily/xpg4" \
    "$1/opt/schily/share/doc/rscsi" \
    "$1/opt/schily/share/doc/rmt" \
    "$1/opt/schily/share/doc/star" \
    "$1/opt/schily/share/doc/bsh" \
    "$1/opt/schily/share/doc/bosh" \
    "$1/opt/schily/share/doc/cdda2wav" \
    "$1/opt/schily/share/doc/libparanoia" \
    "$1/opt/schily/share/man/de" \
    "$1/opt/schily/share/man/man3" \
    "$1/opt/schily/share/man/man5"
