#!/bin/sh -e

make
make install

# Remove documentation (READMEs, etc).
for bin in calltree mt smt sformat sccs; do
    rm -f "$1/opt/schily/bin/$bin"
done

find "$1" -type f -name \*sccs\*   -delete
find "$1" -type f -name \*rmt\*    -delete

for man in admin cdc comb delta get help mountcd prs prt rmdel sact smt mt unget val what; do
    rm -f "$1/opt/schily/share/man/man1/$man.1"
done

rm -f \
    "$1/etc/sformat" \
    "$1/etc/default/rscsi" \
    "$1/opt/schily/share/man/man8/sformat.8"

rm -rf \
    "$1/etc/default/rscsi" \
    "$1/opt/schily/ccs" \
    "$1/opt/schily/sbin" \
    "$1/opt/schily/xpg4" \
    "$1/opt/schily/share/doc/rscsi" \
    "$1/opt/schily/share/doc/rmt" \
    "$1/opt/schily/share/doc/star" \
    "$1/opt/schily/share/doc/bsh" \
    "$1/opt/schily/share/doc/bosh" \
    "$1/opt/schily/share/doc/cdda2wav" \
    "$1/opt/schily/share/doc/libparanoia" \
    "$1/opt/schily/share/man/de" \
    "$1/opt/schily/share/man/man3" \
    "$1/opt/schily/share/man/man5"
