#!/bin/sh -e

cat <<EOF

#######################################

NOTE: To use rbw with caddy add the 'http' or 'https'
      entry to '/etc/caddy/Caddyfile'.

# ------ BEGIN ------ #
# rbw Unofficial Bitwarden CLI
vaultwarden.local:2014 {
	tls internal
	reverse_proxy 127.0.0.1:8000
}

# rbw Unofficial Bitwarden CLI
http://vaultwarden.local:2018 {
	reverse_proxy 127.0.0.1:8000
}

# ------- END ------- #

NOTE: To use 'https' with caddy
      add the requisite export to '.profile'
      or append 'root.crt' to '/etc/ssl/cert.pem'.

# To verify 'https' is working.
-> export SSL_CERT_FILE="/path/to/vaultwarden.local.crt"
-> export SSL_CERT_FILE="/path/to/root.crt"

# Add 'root.crt' to system certificates.
-> cat /etc/ssl/cert.pem root.crt > certupd.pem
-> export SSL_CERT_FILE="/path/to/certupd.pem"

NOTE: Caddy creates its certificates at the following paths.

-> "/var/lib/caddy/.local/share/caddy/pki/authorities/local/root.crt"
-> "/var/lib/caddy/.local/share/caddy/certificates/local/vaultwarden.local/vaultwarden.local.crt"

NOTE: This pinentry error may occur after running 'rbw purge', 'rbw stop-agent' necessitating a 'reboot'.
      "rbw list: failed to read password from pinentry: failed to parse pinentry output ("S ERROR curses.open_tty_for_read 83918849 \nERR 83918849 Permission denied <Pinentry>\n\0\0\0\0\0\0")"

NOTE: The following error message can be resolved by updating rbw and or running 'rbw purge'.
      "WARN: failed to decrypt ...: failed to decrypt: failed to decrypt encrypted secret: invalid mac"

NOTE: Using the '.config/rbw/config.json' option "client_cert_path" causes the following error.
      "rbw login: failed to log in to bitwarden instance: failed to create reqwest client: builder error: unexpected error: private key or certificate not found"

#######################################

EOF
