#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc/tirpc \
    --enable-shared \
    --disable-static \
    --disable-gssapi

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/man/man3"
