#!/bin/sh -e

unzip snapraid-diff-sync/master.zip

# Snapraid's SMART logging appears to be broken, so disable it.
sed 's,SMART_LOG=1,SMART_LOG=0,' snapraid-diff-sync-main/snapraid-diff-sync.sh > _

./configure \
    --prefix=/usr

make
make install

install -Dm644 snapraid.conf.example "$1/etc/snapraid.conf"
install -Dm755 _ "$1/usr/share/snapraid/snapraid-diff-sync.sh"
