#!/bin/sh -e

# Snapraid's SMART logging appears to be broken, so disable it.
sed -i 's,SMART_LOG=1,SMART_LOG=0,' snapraid-diff-sync.sh

./configure \
    --prefix=/usr

make
make install

install -Dm644 snapraid.conf.example "$1/etc/snapraid.conf"
install -Dm755 snapraid-diff-sync.sh "$1/usr/share/snapraid/snapraid-diff-sync.sh"
