#!/bin/sh -e

sed -i "29s|.*|chmod u+s \"\${DESTDIR}\${bindir}/fusermount3\"|" \
    util/install_helper.sh

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dexamples=false \
    -Dsbindir=bin \
    -Dudevrulesdir=/usr/lib/udev \
    -Duseroot=false \
    . output

ninja -C output
ninja -C output install

ln -s fusermount3 "$1/usr/bin/fusermount"

# Remove the unused.
rm -rf "$1/usr/lib/udev" \
       "$1/etc/init.d"
