#!/bin/sh -e
# https://www.linuxfromscratch.org/lfs/view/10.1/chapter08/e2fsprogs.html
#
# Error occurs as USER
# strip: unable to copy file '.../pkg/e2fsprogs/usr/lib/libss.a'; reason: Permission denied
# strip: unable to copy file '.../pkg/e2fsprogs/usr/lib/libext2fs.a'; reason: Permission denied
# strip: unable to copy file '.../pkg/e2fsprogs/usr/lib/libe2p.a'; reason: Permission denied
# strip: unable to copy file '.../pkg/e2fsprogs/usr/lib/libcom_err.a'; reason: Permission denied

export LDFLAGS="$LDFLAGS -static"

sed '268s/444/755/' lib/e2p/Makefile > _
mv -f _ lib/e2p/Makefile

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --enable-symlink-install \
    --enable-libuuid \
    --enable-libblkid \
    --disable-nls \
    --disable-uuidd \
    --disable-fsck \
    --disable-elf-shlibs

make 

set -- \
    MKDIR_P="mkdir -p " \
    BLKID_MAN="" \
    BLKID_PROG="" \
    FINDFS_LINK="" \
    FINDFS_MAN="" \
    UMANPAGES="chattr.1 lsattr.1" \
    UPROGS="chattr lsattr"

for p in \
    debugfs \
    e2fsck \
    lib/e2p \
    lib/et \
    lib/ext2fs \
    lib/ss \
    misc \
    resize \
    scrub
do
    make -C "$p" "$@" install
done
