#!/bin/sh -e

# Switch to coreutils 'ln' due to busybox 'ln'
# lacking the option (-L|--logical).
kiss l coreutils || exit 1

if stat /usr/bin/ln | grep -qo busybox; then
    kiss a coreutils /usr/bin/ln
fi

make
make man

install -Dm644 bower.conf.sample "$1/usr/share/bower/bower.conf"
install -Dm644 bower.1           "$1/usr/share/man/man1/bower.1"
install -Dm755 bower             "$1/usr/bin/bower"

# Restore busybox ln.
if ! stat /usr/bin/ln | grep -qo busybox; then
    kiss a busybox /usr/bin/ln
fi

