#!/bin/sh -e

sed '116s+check_cmd "asciidoctor"+# check_cmd "asciidoctor"+' config.sh > _
mv -f _ config.sh
chmod +x config.sh

make newsboat
make podboat

make DESTDIR="$1" install-newsboat
make DESTDIR="$1" install-podboat
