#!/bin/sh -e

sed 's+/usr/local+/usr+' Makefile > _
mv -f _ Makefile

sed '54s+-O2+-O3+' Makefile > _
mv -f _ Makefile

sed '116s+check_cmd "asciidoctor"+# check_cmd "asciidoctor"+' config.sh > _
mv -f _ config.sh
chmod +x config.sh

make newsboat
make podboat

make DESTDIR="$1" install-newsboat
make DESTDIR="$1" install-podboat
