#!/bin/sh -e

# Change install prefix.
sed 's+/usr/local+/usr+' Makefile > _
mv -f _ Makefile

# Remove asciidoctor check.
sed '116d' config.sh > _
mv -f _ config.sh

chmod +x config.sh

make newsboat
make podboat

make DESTDIR="$1" install-newsboat
make DESTDIR="$1" install-podboat
