#!/bin/sh -e

# Static build fails
# .../usr/lib/libreadline.a': No such file or directory
# .../usr/lib/libhistory.a': No such file or directory

./configure \
    --prefix=/usr \
    --enable-static=no
    
make SHLIB_LIBS=-lncurses
make DESTDIR="$1" install
