#!/bin/sh -e

# Static build initially failed.
# .../usr/lib/libreadline.a': No such file or directory
# .../usr/lib/libhistory.a': No such file or directory

./configure \
    --prefix=/usr \
    --enable-static \
    --enable-shared

make SHLIB_LIBS=-lncursesw
make DESTDIR="$1" install

# Remove documentation.
rm -rf \
     "$1/usr/share/doc" \
     "$1/usr/share/info"
