#!/bin/sh -e

# Static build fails
# .../usr/lib/libreadline.a': No such file or directory
# .../usr/lib/libhistory.a': No such file or directory

./configure \
    --prefix=/usr \
    --enable-static=no
    
make
make DESTDIR="$1" install

if [ -d /var/db/kiss/installed/libedit && /usr/share/man/man3/history.3 ]; then
rm $1/usr/share/man/man3/history.3
fi
