#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

make prefix=/usr \
    NO_REGEX=NeedsStartEnd \
    NO_GETTEXT=YesPlease \
    NO_SVN_TESTS=YesPlease \
    NO_TCLTK=YesPlease \
    NO_EXPAT=YesPlease \
    NO_NSEC=YesPlease \
    NO_PYTHON=YesPlease \
    NO_PERL=YesPlease \
    NO_SYS_POLL_H=1 \
    NO_CROSS_DIRECTORY_HARDLINKS=1 \
    NO_INSTALL_HARDLINKS=1 \
    AC_CV_LIB_CURL_CURL_GLOBAL_INIT=YES \
    AC_CV_SNPRINTF_RETURNS_BOGUS=NO \
    AC_CV_FREAD_READS_DIRECTORIES=YES

make prefix=/usr \
    NO_REGEX=NeedsStartEnd \
    NO_GETTEXT=YesPlease \
    NO_SVN_TESTS=YesPlease \
    NO_TCLTK=YesPlease \
    NO_EXPAT=YesPlease \
    NO_NSEC=YesPlease \
    NO_PYTHON=YesPlease \
    NO_PERL=YesPlease \
    NO_SYS_POLL_H=1 \
    NO_CROSS_DIRECTORY_HARDLINKS=1 \
    NO_INSTALL_HARDLINKS=1 \
    AC_CV_LIB_CURL_CURL_GLOBAL_INIT=YES \
    AC_CV_SNPRINTF_RETURNS_BOGUS=NO \
    AC_CV_FREAD_READS_DIRECTORIES=YES \
    LIBS="$(curl-config --static-libs) libgit.a xdiff/lib.a -lz" \
    install
