#!/bin/sh -e

for opt in '#user=jmaggard+user=minidlna' '#log_dir=/var/log+log_dir=/var/log' '#db_dir=/v ar/cache/minidlna+db_dir=/var/lib/minidlna'; do
   sed "s+$opt+" etc/minidlna.conf > _
done

install -Dm755 usr/sbin/minidlnad "$1/usr/bin/minidlnad-bin"
install -Dm644 _ "$1/etc/minidlna.conf"
install -Dm755 minidlnad.run "$1/etc/sv/minidlnad-bin/run"

# Install runit service.
install -dm755 "$1/var/service"
ln -sf /etc/sv/minidlnad-bin "$1/var/service/"
ln -sf "/run/runit/supervise.minidlna-bin" "$1/etc/sv/minidlna-bin/supervise"
