#!/bin/sh -e

sed -e 's+#user=jmaggard+user=minidlna+' \
    -e 's+#log_dir=/var/log+log_dir=/var/log+' \
    -e 's+#db_dir=/var/cache/minidlna+db_dir=/var/lib/minidlna+' etc/minidlna.conf > _

install -Dm755 usr/sbin/minidlnad "$1/usr/bin/minidlnad"
install -Dm644 _                  "$1/etc/minidlna.conf"
install -Dm755 minidlnad.run      "$1/etc/sv/minidlna/run"
