#!/bin/sh -e

if [ ! -d /var/db/kiss/installed/readymedia ]; then
   status=$(cat /etc/sv/minidlna/supervise/stat)
   [ "$status" = "run" ] && sv down minidlna
   unlink /var/service/minidlna
   deluser --remove-home minidlna

   rm -r \
       "/etc/sv/minidlna" \
       "/run/runit/supervise.minidlna"
fi
