#!/bin/sh -e

if ! kiss l readymedia; then
    status=$(cat /etc/sv/minidlna/supervise/stat)
    [ "$status" = "run" ] && sv down minidlna
    deluser --remove-home minidlna

    rm -rf \
        "/etc/sv/minidlna" \
        "/run/runit/supervise.minidlna" \
        "/var/service/minidlna"
fi
