#!/bin/sh -e

if ! kiss l readymedia; then
    if [ -L "/var/service/minidlna" ]; then
        sv down minidlna
        unlink "/var/service/minidlna"
    fi

    deluser --remove-home minidlna

    rm -rf \
        "/etc/sv/minidlna" \
        "/run/runit/supervise.minidlna"
fi
