#!/bin/sh -e

./configure \
    --cc="$CC" \
    --cxx="$CXX" \
    --prefix=/usr \
    --x86asmexe=nasm \
    --disable-debug \
    --disable-libxml2 \
    --disable-libxcb \
    --disable-libxcb-shm \
    --disable-libxcb-xfixes \
    --disable-libxcb-shape \
    --disable-shared \
    --disable-xlib \
    --disable-alsa \
    --disable-static \
    --disable-indev=oss \
    --disable-outdev=oss \
    --disable-runtime-cpudetect \
    --enable-gpl \
    --enable-sndio \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-nonfree \
    --enable-openssl \
    --enable-shared \
    --enable-libass
#   --enable-libdrm

make
make install

rm -rf "$1/usr/share/ffmpeg/examples"
