#!/bin/sh -e

# The use of CFLAGS='-pipe' can cause 'xfsdump' to fail
# building due to sharing the same build folder as 'xfsprogs'.
#
# The -pipe failure can be fixed by
# removing the 'xfsprogs' build folder.
if [ -d ../xfsprogs ]; then
    rm -rf ../xfsprogs
fi

# Building xfsdump statically requires
# the double hyphen --static.
make \
    LDFLAGS=--static \
    DEBUG=-DNDEBUG \
    LOCAL_CONFIGURE_OPTIONS="--prefix=/usr \
                             --sbindir=/usr/bin \
                             --enable-lib64=no \
                             --disable-gettext"

# Remove 'bash' dependency.
sed -i 's/bash/sh/' install-sh

make DESTDIR="$1" install

# Fix broken --sbindir.
mv "$1/sbin/"* "$1/usr/bin"
rmdir "$1/sbin"

# Remove documentation (README's & such).
rm -rf "$1/usr/share/doc"
