#!/bin/sh -e

cp makefile.linux_amd64_asm makefile.machine

sed 's/OPTFLAGS=-O -s/OPTFLAGS=-O3 -pipe -march=native -s/' makefile.machine > _
mv -f _ makefile.machine

make all3
make DESTDIR="$1" install
