#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --disable-otp \
    --enable-login

make
make DESTDIR="$1" install

# Remove docs.
rm -rf "$1/usr/share/man/man3"
