#!/bin/sh -e

./configure \
    --prefix=/usr \
    --without-readline \
    --without-editline \
    --enable-lto

make \
    PARALLEL="-j$(nproc)" \
    LIBGRADES="hlc.gc" \
    DESTDIR="$PWD" \
    install

for bin in c2init canonical_grade mdb mdemangle mercury_compile mercury_config mfiltercc mfilterjavac mgnuc mkinit ml mmake mmc mtags; do
    install -D "usr/bin/$bin" "$1/usr/bin/$bin"
done

for man in c2init.1 mdb.1 mercury_config.1 mgnuc.1 ml.1 mmake.1 mmc.1 mtags.1; do
    install -D "usr/share/man/man1/$man" "$1/usr/share/man/man1/$man"
done

for grade in hlc.gc; do
    install -D -t "$1/usr/lib/mercury/lib/$grade"     usr/lib/mercury/lib/$grade/lib*.so
    install -D -t "$1/usr/lib/mercury/lib/$grade"     usr/lib/mercury/lib/$grade/lib*.a
    install -D -t "$1/usr/lib/mercury/modules/$grade" usr/lib/mercury/modules/$grade/*.init
    cp      -R -t "$1/usr/lib/mercury/lib/$grade"     usr/lib/mercury/lib/$grade/inc
done

for dir in ints inc mdb mmake; do
    cp -R "usr/lib/mercury/$dir" "$1/usr/lib/mercury/$dir"
done

install -D -t "$1/usr/lib/mercury/conf" \
              usr/lib/mercury/conf/Mercury.config \
              usr/lib/mercury/conf/mercury_conf.h

install -D -t "$1/usr/lib/mercury/lib" \
              usr/lib/mercury/lib/libgc.a
              usr/lib/mercury/lib/libgc.so

rm -rf \
    "$1/usr/lib/mercury/ints/hlc.gc.pregen" \
    "$1/usr/lib/mercury/lib/hlc.gc.pregen"
