#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --mandir=/usr/share/man \
    --disable-nls \
    --disable-rpath \
    --enable-lto

make
make install

sed -i \
    -e 's+#user=jmaggard+user=minidlna+' \
    -e 's+#log_dir=/var/log+log_dir=/var/log+' \
    -e 's+#db_dir=/var/cache/minidlna+db_dir=/var/lib/minidlna+' minidlna.conf

install -Dm644 minidlna.conf   "$1/etc/minidlna.conf"
install -Dm644 minidlna.conf.5 "$1/usr/share/man/man5/minidlna.conf.5"
install -Dm644 minidlnad.8     "$1/usr/share/man/man8/minidlnad.8"

# Install runit service.
install -Dm755 minidlnad.run "$1/etc/sv/minidlna/run"
ln -sf /run/runit/supervise.minidlna /etc/sv/minidlna/supervise

