#!/bin/sh -e 

# Fix undefined reference to major
sed s'+#include <sys/stat.h>+#include <sys/stat.h>\
#include <sys/sysmacros.h>+' extlinux/main.c > _
mv -f _ extlinux/main.c

make bios installer

# Install ldlinux.c32 & ldlinux.sys
# extlinux --install /boot/extlinux --device /dev/sda1
mkdir -p $1/boot/extlinux
bios/extlinux/extlinux --install $1/boot/extlinux

for f in altmbr.bin gptmbr.bin mbr.bin; do
install -Dm644 bios/mbr/$f $1/usr/share/syslinux/$f
done

install -Dm644 bios/com32/libutil/libutil.c32 $1/boot/extlinux
install -Dm644 bios/com32/lib/libcom32.c32 $1/boot/extlinux
install -Dm644 bios/com32/menu/menu.c32 $1/boot/extlinux
install -Dm644 bios/com32/menu/vesamenu.c32 $1/boot/extlinux
install -Dm644 sample/syslinux_splash.jpg $1/boot/extlinux
install -Dm644 sample/m16-640x640-syslinux.jpg $1/boot/extlinux

install -Dm644 extlinux.conf $1/boot/extlinux
partuuid=$(blkid -s PARTUUID -o value /dev/sda1)
echo "append root=PARTUUID=$partuuid ro" >> $1/boot/extlinux/extlinux.conf

echo "[!] INSTALLATION OF MASTER BOOT RECORD [!]"
echo ""
echo "[!] WARNING [!]"
echo "VERIFY '/dev/sda' IS THE CORRECT LOCATION FOR mbr.bin"
echo ""
echo "Note: https://wiki.syslinux.org/wiki/index.php?title=Mbr"
echo "      dd is the "safe approach"
echo "" 
echo "Use 'cat mbr.bin > /dev/sda' or 'dd bs=440 count=1 if=mbr.bin of=/dev/sda'"
