#!/bin/sh -e

mkdir -p $1/boot/extlinux 

# fix undefined reference to major
sed '/#include <sys/stat.h>/a #include <sys/sysmacros.h>' extlinux/main.c > _
mv -f _ extlinux/main.c

make bios installer

# install master boot record
# Note: https://wiki.syslinux.org/wiki/index.php?title=Mbr
#       dd is the "safe approach"
# cat mbr.bin > /dev/sda 
# dd bs=440 count=1 if=mbr/mbr.bin of=/dev/sda

# install ldlinux.c32 & ldlinux.sys
# extlinux --install /boot/extlinux --device /dev/sda1
extlinux/extlinux --install $1/boot/extlinux

install -Dm644 bios/com32/libutil/libutil.c32 $1/boot/extlinux/libutil.c32
install -Dm644 bios/com32/lib/libcom32.c32 $1/boot/extlinux/libcom32.c32
install -Dm644 bios/com32/menu/menu.c32 $1/boot/extlinux/menu.c32
install -Dm644 bios/com32/menu/vesamenu.c32 $1/boot/extlinux/vesamenu.c32
install -Dm644 sample/syslinux_splash.jpg $1/boot/extlinux/syslinux_splash.jpg
install -Dm644 sample/m16-640x640-syslinux.jpg $1/boot/extlinux/m16-640x640-syslinux.jpg

install -Dm644 extlinux.conf $1/boot/extlinux/extlinux.conf
partuuid=$(blkid -s PARTUUID -o value /dev/sda1)
echo "append root=PARTUUID=$partuuid ro" >> $1/boot/extlinux/extlinux.conf
