#!/bin/sh -e

if [ "$(id -u)" != 0 ]; then
   echo "#####################################"
   echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
   echo "#                                   #"
   echo "#      ssu -p kiss b femtomail      #"
   echo "#####################################"

   exit 1
fi

[ -L /usr/bin/sendmail ] && unlink /usr/bin/sendmail

# Change install location from /usr/sbin to /usr/bin
sed 's+/usr/sbin+/usr/bin+g' Makefile > _
mv -f _ Makefile

make USERNAME=root MAILBOX_PATH=/var/mail
make install install-link-sendmail

install -dm755 "$1/var/mail/new"
