#!/bin/sh -e

echo "#####################################"
echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
echo "#                                   #"
echo "#        ssu -p b femtomail         #"
echo "#####################################"

[ -f /usr/bin/sendmail ] && unlink /usr/bin/sendmail

# Change install location from /usr/sbin to /usr/bin
sed 's+/usr/sbin+/usr/bin+g' Makefile > _
mv -f _ Makefile

sed 's+-O2++g' Makefile > _
mv -f _ Makefile

make USERNAME=root MAILBOX_PATH=/var/mail
make install install-link-sendmail setcap

install -dm755 $1/var/mail/new
