#!/bin/sh -e

[ -f /usr/bin/sendmail ] && unlink /usr/bin/sendmail

# Change install location from /usr/sbin to /usr/bin
sed 's+/usr/sbin+/usr/bin+g' Makefile > _
mv -f _ Makefile

make USERNAME=root MAILBOX_PATH=/var/mail
make install install-link-sendmail setcap

mkdir -p /var/mail/new
