#!/bin/sh -e

if [ "$(id -u)" != 0 ]; then
   echo "#####################################"
   echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
   echo "#                                   #"
   echo "#       ssu -p kiss b restic        #"
   echo "#####################################"

   exit 1
fi

make

install -Dm755 restic "$1/usr/bin/restic"
install -Dm644 -t "$1/usr/share/man/man1/" doc/man/*.1
install -Dm644 doc/bash-completion.sh "$1/usr/share/bash-completion/completions/restic"
