#!/bin/sh -e

./configure \
   --prefix=/usr \
   --disable-nls \
   --with-nettle-mini \
   --with-included-libtasn1 \
   --with-included-unistring \
   --enable-static \
   --without-p11-kit

make
make DESTDIR="$1" install

# Remove man3 + png's.
rm -rf \
     "$1/usr/share/doc" \
     "$1/usr/share/man/man3"
