#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-static \
    --enable-shared \
    --disable-zlib \
    --disable-bzlib \
    --disable-xzlib \
    --disable-zstdlib \
    --disable-lzlib \
    --disable-lrziplib \
    --datadir=/usr/share/file \
    --disable-dependency-tracking

make
make install

# Remove documentation.
rm -rf \
    "$1/usr/share/man/man3" \
    "$1/usr/share/man/man4" \
    "$1/usr/share/man/man5"

