#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbin=/usr/bin \
    --with-mapdir=/etc/autofs \
    --with-confdir=/etc/autofs \
    --without-openldap \
    --without-sasl \
    --with-libtirpc \
    --disable-fedfs \
    --enable-ignore-busy \
    --enable-force-shutdown

# Prevent libxml2 from being pulled in.
sed -i '/#define LIBXML2_WORKAROUND/d' include/config.h

make
make install

install -Dm755 autofs.run "$1/etc/sv/autofs/run"
install -Dm644 samples/autofs.conf.default "$1/etc/autofs/autofs.conf"

install -dm755 "$1/usr/share/autofs/samples"
install -m644 samples/auto.master \
              samples/auto.misc \
              samples/auto.net \
              samples/auto.smb \
              samples/autofs.conf.default \
              samples/autofs.init.conf \
              samples/rc.autofs "$1/usr/share/autofs/samples"

# Create link to satisfy startup check.
ln -sf /etc/autofs/autofs.conf "$1/etc/autofs/autofs"

rm "$1/usr/share/man/man5/autofs_ldap_auth.conf.5"
