#!/bin/sh -e

patch -p1 < libtheora-1.1.1-libpng16.patch

# libtheora-1.1.0 builds with 'fix-theoraenc.patch',
# however libtheora-1.1.1 fails to build.
# patch -p1 < fix-theoraenc.patch

./configure \
    --prefix=/usr

make
make -C lib     install
make -C include install
make install-pkgconfigDATA
