#!/bin/sh -e

sed '12,15d' examplescripts/Example7 > _
mv -f _ examplescripts/Example7

sed '23s+DEVICESCAN+DEVICESCAN -m root -M exec /usr/share/doc/smartmontools/examplescripts/Example7+' smartd.conf > _
mv -f _ smartd.conf

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc/smartd

make
make install

# Install runit service.
install -Dm755 smartd.run    "$1/etc/sv/smartd/run"
install -Dm755 smartd.finish "$1/etc/sv/smartd/finish"
ln -sf /run/runit/supervise.smartd "$1/etc/sv/smartd/supervise"
