#!/bin/sh

cat <<EOF

################################################

NOTE: 'Busybox diff' conflicts with 'Diffutils sdiff'.

      To use sdiff, swap 'Busybox diff' with 'Diffutils diff'.
      -> kiss a diffutils /usr/bin/diff

################################################

EOF
