#!/bin/sh

cat <<EOF

#################
    IMPORTANT
#################

To use sdiff, swap 'busybox diff' with 'diffutils diff'

-> kiss a diffutils /usr/bin/diff

NOTE: 'busybox diff' conflicts with 'diffutils sdiff'.

#################
