#!/bin/sh -ef

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/doc/kiss/init"

# Add tty6.
sed -i '/ tty5/a\tty6::respawn:/bin/getty 38400 tty6'
# Re-locate kernel log to tty6.
sed -i '/iwlwifi/a\::once:/bin/setlogcons 6' etc/inittab

cp -R etc "$1"
cp -R lib "$1/usr/lib"

# Disable warning as CFLAGS must work this way.
# shellcheck disable=2086
for bin in kpow kall; do
    "$CC" -o "$1/usr/bin/$bin" "bin/$bin.c" $CFLAGS -static
    cp -f "bin/$bin.c" "$1/usr/share/doc/kiss/init/$bin.c"
done
