#!/bin/sh -e

# Remove obsolete program.
sed '/RESIZECONS_PROGS=/s/yes/no/' configure > _
mv -f _ configure
chmod +x configure

sed 's/resizecons.8 //' docs/man/man8/Makefile.in > _
mv -f _ docs/man/man8/Makefile.in

./configure \
    --prefix=/usr \
    --datadir=/usr/share/kbd \
    --disable-vlock \
    --disable-tests

make
make install

{
    # Purge unused languages, fonts etc.
    cd "$1/usr/share/kbd/consolefonts"

    rm -rf \
        "$1/usr/share/locale" \
        "$1/usr/share/kbd/keymaps" \
        ERRORS \
        README.Arabic \
        README.Cyrillic \
        README.Ethiopic\
        README.Greek \
        README.Hebrew \
        README.LatGrkCyr \
        README.drdos \
        README.eurlatgr \
        README.eurlatgr.mappings \
        Agafari* koi8* Goha* *Cyr* *cyr* gr* ruscii*
}
