#!/bin/sh -e

# Fix permission errors
sed '42s/555/755/' GNUmakefile > _
mv -f _ GNUmakefile

sed '43s/444/755/' GNUmakefile > _
mv -f _ GNUmakefile

sed 's+.siren+.cache/siren+' siren.h > _
mv -f _ siren.h

./configure \
    prefix=/usr \
    bindir=/usr/bin \
    mandir=/usr/share/man \
    plugindir=/usr/lib/siren \
    debug=no \
    aac=yes \
    mad=no \
    sndio=yes \
    ffmpeg=yes \
    mpg123=yes \
    flac=yes \
    opus=yes \
    sndfile=yes \
    vorbis=yes \
    wavpack=yes \
    sun=no \
    oss=no \
    ao=no \
    portaudio=no \
    pulse=no \
    alsa=no
      
make
make install

chmod 444 $1/usr/lib/siren/ip/*
chmod 555 $1/usr/bin/siren
