#!/bin/sh -e

UID="$(id | cut -d "(" -f 1)"

#if [ "$UID" != uid=0 ]; then
echo "#####################################"
echo "# [ ! ] NEED TO BUILD AS ROOT [ ! ] #"
echo "#                                   #"
echo "#        ssu -p kiss b siren        #"
echo "#####################################"
sleep 1
#exit 1
#fi

# Fix permission errors
#sed '42s/555/755/' GNUmakefile > _
#mv -f _ GNUmakefile

#sed '43s/444/755/' GNUmakefile > _
#mv -f _ GNUmakefile

# Change metadata location
sed 's+.siren+.cache/siren+' siren.h > _
mv -f _ siren.h

./configure \
    prefix=/usr \
    bindir=/usr/bin \
    mandir=/usr/share/man \
    plugindir=/usr/lib/siren \
    debug=no \
    aac=yes \
    mad=no \
    sndio=yes \
    ffmpeg=yes \
    mpg123=yes \
    flac=yes \
    opus=yes \
    sndfile=yes \
    vorbis=yes \
    wavpack=yes \
    sun=no \
    oss=no \
    ao=no \
    portaudio=no \
    pulse=no \
    alsa=no
      
make
make install

#chmod 444 "$DESTDIR/usr/lib/siren/ip/"*
#chmod 555 "$DESTDIR/usr/bin/siren"
