#!/bin/sh -e

./configure 
    --prefix=/usr \
    --bindir=/bin \
    --mandir=/share/man \
    --plugindir=/lib/siren \
    --debug=no \
      aac=yes \
      mad=no \
      sndio=yes \
      ffmpeg=yes \
      mpg123=yes \
      flac=yes \
      opus=yes \
      sndfile=yes \
      vorbis=yes \
      wavpack=yes \
      sun=no \
      oss=no \
      ao=no \
      portaudio=no \
      pulse=no \
      alsa=no
      
 make
 make install
