#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-nls

make
make install

install -Dm644 -t "$1/usr/share/doc/msmtp" doc/msmtprc-system.example
install -Dm644 -t "$1/usr/share/doc/msmtp" doc/msmtprc-user.example
