#!/bin/sh -e

# Fix build when libatomic.so does not exist in the system.
# This may be provided by compiler-rt which requires no additional
# linker flags to be used.
[ -r "$KISS_ROOT/usr/lib/libatomic.so" ] || {
    sed 's/-latomic//' node.gyp > _
    mv -f _ node.gyp
}

# nodejs 18.4.2 LTS
# -march=native fails to build with core2
march=$(gcc -march=native -Q --help=target | grep -- -march | grep -o core2 || true)

if [ "$march" ]; then
   export CXXFLAGS="$CXXFLAGS -march=$march"
fi

./configure \
    --shared-zlib \
    --shared-openssl \
    --with-intl=none \
    --without-etw \
    --without-dtrace \
    --without-report \
    --without-node-snapshot \
    --without-node-code-cache \
    --ninja

ninja -C out/Release
tools/install.py install "$1" /usr

# Remove unneeded files.
rm -rf \
    "$1/usr/include/node/openssl" \
    "$1/usr/share/doc" \
    "$1/usr/share/systemtap" \
    "$1/usr/lib/node_modules/npm/scripts" \
    "$1/usr/lib/node_modules/npm/configure"
