#!/bin/sh -e

sed 's#<ncursesw/ncurses.h>#<ncurses.h>#' gptcurses.cc > _
mv -f _ gptcurses.cc

make

for f in gdisk cgdisk sgdisk fixparts; do
install -Dm755 $f $1/usr/bin/$f
done

for f in *.8; do
install -Dm644 $f $1/usr/share/man/man8/$f
done
