#!/bin/sh -e

sed 's#<ncursesw/ncurses.h>#<ncurses.h>#' gptcurses.cc > _
mv -f _ gptcurses.cc

make

install -Dm755 -t "$1/usr/bin" gdisk cgdisk sgdisk fixparts
install -Dm644 -t "$1/usr/share/man/man8" *.8

