#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/sbin \
    --enable-libipq \
    --with-xtlibdir=/lib/xtables \
    --disable-nftables

make
make DESTDIR="$1" install

# Remove man3.
rm -rf "$1/usr/share/man/man3"
