#!/bin/sh -e

cat <<'EOF'
#########################################################################################

# Add the following to "$HOME/.profile to start starship on login"
eval "$(starship-bin init bash)"
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# Add starship config to "$HOME/.config/starship"
mkdir -p "$HOME/.config/starship"
ln -s /usr/share/starship/starship.toml.plain-text "$HOME/.config/starship/starship.toml"

#########################################################################################
EOF
