#!/bin/sh -e

# NOTE: The single quotes 'EOF' prevent eval from expanding.

cat <<'EOF'

############################################################################################

NOTE: To start starship on login add this to '.profile'.

-> eval "$(starship init bash)"
-> export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

NOTE: Create starship config

-> mkdir -p "$HOME/.config/starship"
-> ln -s /usr/share/starship/starship.toml.plain-text "$HOME/.config/starship/starship.toml"

############################################################################################

EOF
