#!/bin/sh -e

./configure \
   --prefix=/usr \
   --sbindir=/usr/bin \
   --sysconfdir=/etc \
   --localstatedir=/var/lib/netatalk \
   --with-ssl-dir=/usr/lib/ssl \
   --with-bdb=/opt/BerkeleyDB.6.0 \
   --without-cnid-tdb-backend \
   --disable-quota

make
make install

# Remove the unneeded
rm -rf "$1/usr/include/atalk"
rm -f "$1/usr/bin/afpldaptest"
rm -f "$1/usr/bin/lp2pap.sh"
rm -rf "$1/usr/lib"
