#!/bin/sh

cat <<EOF

###############################################

NOTE: To start netatalk at boot add this to
      '/etc/rc.d/setup.boot'

-> 'cnid_metad'
-> 'afpd'

NOTE: 'cnid_metad' needs to start before 'afpd'

###############################################

EOF
