#!/bin/sh -e
# Remove incorrect bash dependency.
sed -i 's/bash/sh/' install-sh
        
./configure \
   --prefix=/usr \
   --sbindir=/bin \
   --disable-gettext \
   --enable-lto \
   --enable-editline=yes

make DEBUG=-DNDEBUG

make \
DIST_ROOT="$1" \
PKG_ROOT_SBIN_DIR=/usr/bin \
PKG_ROOT_LIB_DIR=/lib \
install
