#!/bin/sh -e

# To avoid using the default OPTIMIZER
# values an empty value is needed.
export OPTIMIZER=" "

# Remove 'bash' dependency.
sed 's/bash/sh/' install-sh > _
mv -f _ install-sh

chmod +x install-sh

# To build binaries statically the
# shared libraries also need to be built.
# --enable-static & --enable-shared (is the default).
./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --enable-lib64=no \
    --disable-gettext \
    --enable-lto

make \
    DEBUG=-DNDEBUG \
    LDFLAGS=-all-static

make \
    DIST_ROOT="$1" \
    PKG_ROOT_SBIN_DIR=/usr/bin \
    PKG_ROOT_LIB_DIR=/usr/lib \
install \
install-dev

# Remove documentation (README, crontab & such).
echo rm -rf \
    "$1/usr/lib/xfsprogs" \
    "$1/usr/share/doc" \
    "$1/usr/share/man/man2" \
    "$1/usr/share/man/man3"

# Remove libhandle.so's as xfsdump will
# be built statically with libhandle.a.
rm -f \
    "$1/usr/lib/"libhandle.so* \
    "$1/usr/share/man/man5/"proj*.5
