#!/bin/sh -e

# Remove incorrect bash dependency.
sed 's/bash/sh/' install-sh > _
mv -f _ install-sh

chmod +x install-sh

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --enable-lib64=no \
    --disable-gettext \
    --enable-lto \
    --enable-editline=yes

make DEBUG=-DNDEBUG

make \
    DIST_ROOT="$1" \
    PKG_ROOT_SBIN_DIR=/usr/bin \
    PKG_ROOT_LIB_DIR=/usr/lib \
install \
install-dev

# Remove docs.
rm -f "$1/usr/share/man/man5/"proj*.5

rm -rf "$1/usr/share/doc" \
       "$1/usr/share/man/man2" \
       "$1/usr/share/man/man3"
