#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --disable-nls \
    --disable-rpath

make
make install

# Remove mans & udev rule.
rm -rf "$1/usr/share/man/fr"
rm -rf "$1/usr/share/man/man7"
rm -rf "$1/lib"
