#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --disable-nls \
    --disable-rpath

make
make install

# Remove manpages & udev rule.
rm -rf \
    "$1/usr/share/man/fr" \
    "$1/usr/share/man/man7" \
    "$1/lib"
