#!/bin/sh -e

cat <<EOF

################################

NOTE: 'aplay' requires 'mdev{d}'
      to list USB sound cards.

NOTE: Useage examples.

-> aplay -D plughw:CARD=2 file.wav
-> speaker-test -D plughw:CARD=2 -c2

NOTE: To set a default sound card add
      this to '~/.asoundrc'.

    # ------ BEGIN ------ #
      defaults.pcm.card 2
      defaults.ctl.card 2
    # ------- END ------- #

################################

EOF
