#!/bin/sh -e

mkdir -p junk

(
    cd skalibs

    ./configure \
        --prefix=/usr \
        --disable-shared

    make
    make DESTDIR="$PWD/../junk" install
)

./configure \
    --prefix=/usr \
    --enable-static-libc \
    --disable-shared \
    --with-sysdeps="$PWD/junk/usr/lib/skalibs/sysdeps" \
    --with-lib="$PWD/junk/usr/lib/skalibs" \
    --with-include="$PWD/junk/usr/include"

make
make install

install -Dm644 mdevd.conf     "$1/etc/mdevd.conf"
install -Dm755 mdevd.run      "$1/etc/sv/mdevd/run"
install -Dm755 automounter.sh "$1/usr/lib/mdev/automounter.sh"

# Install runit service.
ln -sf /run/runit/supervise.mdevd "$1/etc/sv/mdevd/supervise"
# Purge config.h.
rm -rf "$1/usr/include"
